### ISSUE TITLE
Error characters for CJK Radicals Supplement

### ISSUE THREAD

**Issue by svenper** [saigyo/common-chinese-radicals#1]
Characters from the Unicode block *CJK Radicals Supplement* [<span lang="zh">⺌⺗⺧⺮⺶⺷⻊</span>] are showing up as black squares.

My intuition is that xeCJK is not treating that block as characters to apply the CJK fonts to.

This could very well be specific to my setup. Are you having the same problem or should I investigate this elsewhere?

![k](https://user-images.githubusercontent.com/15199675/55843799-9c904c80-5b29-11e9-8279-86d4d809529f.png)

---

Void Linux
linux 4.14.111
musl libc 1.1.21

```none
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/Void)
kpathsea version 6.3.1
[©]
Compiled with ICU version 63.1; using 63.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.9.1; using 2.9.1
Compiled with Graphite2 version 1.3.13; using 1.3.13
Compiled with HarfBuzz version 2.4.0; using 2.4.0
Compiled with libpng version 1.6.36; using 1.6.36
Compiled with poppler version 0.75.0
Compiled with fontconfig version 2.13.1; using 2.13.1
```

**Comment by saigyo** [comment]
Hi @svenper, thanks for pointing this out, and sorry for the very late response.

I took your issue as an opportunity to adjust the source so that the file can be typeset on other systems than macOS.
With #2 first I replaced the commercial Myriad Pro font with the free Google Noto font. 
For the CJK-Font, the source originally referenced the Kaiti SC font, which comes readily installed on macOS,
and which seems to be fairly complete when it comes to the CJK Radicals Supplement characters.

With the help of the [GitHub Action for LaTeX](https://github.com/marketplace/actions/github-action-for-latex) I was able to try out different options for typesetting the document in a Linux enviroment (the underlying image uses Alpine Linux). At the end I could only get the radical characters you pointed out by using the original Adobe Kaiti Regular font (pulling it from a [slightly dubious GitHub Repo](https://github.com/dolbydu/font)). With both KaiTi oder STKaiti I get 
nothing or the typical "unicode box" character. 

Obviously, one could also use Noto Sans CJK for the entire document, but it's Chinese characters just don't look as 
pleasing to the eye as the Kaiti-Characters 😄 .

<img width="1194" alt="Bildschirmfoto 2021-05-02 um 16 36 24" src="https://user-images.githubusercontent.com/7271174/116816979-9502cc80-ab64-11eb-992f-c623a311f13b.png">
